In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np

In [3]:
import os
def get_file_length(file_path):
    path, dirs, files = next(os.walk(file_path))
    count = len(files)
    #print(count)
    return count


In [4]:
def get_labels(c1,c2,c3,c4,c5):
    labels = np.zeros((c1,1))
    labels = np.concatenate((labels,np.ones((c2,1))))
    labels = np.concatenate((labels,2*np.ones((c3,1))))
    labels = np.concatenate((labels,3*np.ones((c4,1))))
    labels = np.concatenate((labels,4*np.ones((c5,1))))
    #print(labels.shape)
    return labels


In [5]:
# File Length 
belly_pain_count_test = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/test/belly_pain')
burping_count_test = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/test/burping')
discomfort_count_test = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/test/discomfort')
hungry_count_test = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/test/hungry')
tired_count_test = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/test/tired')
belly_pain_count_train = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/train/belly_pain')
burping_count_train = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/train/burping')
discomfort_count_train = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/train/discomfort')
hungry_count_train = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/train/hungry')
tired_count_train = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/train/tired')
belly_pain_count_valid = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/val/belly_pain')
burping_count_valid = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/val/burping')
discomfort_count_valid = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/val/discomfort')
hungry_count_valid = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/val/hungry')
tired_count_valid = get_file_length(r'/content/drive/My Drive/Baby Cry/68features/val/tired')

In [6]:
labels_test = get_labels(belly_pain_count_test , burping_count_test , discomfort_count_test , hungry_count_test , tired_count_test)
labels_train = get_labels(belly_pain_count_train , burping_count_train , discomfort_count_train , hungry_count_train , tired_count_train)
labels_val = get_labels(belly_pain_count_valid , burping_count_valid , discomfort_count_valid , hungry_count_valid , tired_count_valid)

In [7]:
print(labels_test.shape)

(152, 1)


In [8]:
labels_train = np.append(labels_train,labels_val)

print(labels_train.shape)

(605,)


In [9]:
labels_train = np.reshape(labels_train,(labels_train.shape[0],1))
print(labels_train.shape)

(605, 1)


In [10]:
#from python_speech_features import mfcc
#from python_speech_features import logfeatures
import scipy.io.wavfile as wav
import numpy
import os
import csv
import numpy as np


def get_features_array(dir):
    features = np.zeros((68,199,1))
    for folder in os.listdir(dir):
        folder_path = os.path.join(dir,folder)
        print(folder )
        i = 0
        for filename in os.listdir(folder_path):
            if filename.endswith('.csv'):
                i = i+1
                file_path = os.path.join(folder_path,filename)
                temp = np.genfromtxt(file_path, delimiter=",", skip_header = False)
                temp  = np.reshape(temp,(temp.shape[0],temp.shape[1],1))
                #print(temp.shape)
                features = np.append(features,temp,axis = 2)
                #print(mfcc.shape)
        print(str(folder)+ ' has ' + str(i) + ' files ' )
    features = np.reshape(features,(features.shape[2],features.shape[0],features.shape[1]))
    features = np.delete(features,0,axis = 0)
    return(features)

features_test = get_features_array(r'/content/drive/My Drive/Baby Cry/68features/test')
print(features_test.shape)
features_train = get_features_array(r'/content/drive/My Drive/Baby Cry/68features/train')
print(features_train.shape)
features_val = get_features_array(r'/content/drive/My Drive/Baby Cry/68features/val')
print(features_val.shape)    
        

belly_pain
belly_pain has 16 files 
burping
burping has 8 files 
discomfort
discomfort has 27 files 
hungry
hungry has 77 files 
tired
tired has 24 files 
(152, 68, 199)
belly_pain
belly_pain has 48 files 
burping
burping has 24 files 
discomfort
discomfort has 81 files 
hungry
hungry has 229 files 
tired
tired has 72 files 
(454, 68, 199)
belly_pain
belly_pain has 16 files 
burping
burping has 8 files 
discomfort
discomfort has 27 files 
hungry
hungry has 76 files 
tired
tired has 24 files 
(151, 68, 199)


In [11]:
test_array = np.transpose(features_test, (0, 2, 1))
print(test_array.shape)
train_array = np.transpose(features_train, (0, 2, 1))
valid_array = np.transpose(features_val, (0, 2, 1))

(152, 199, 68)


In [12]:
mean_train = np.reshape(np.mean(train_array,axis = 1),(train_array.shape[0],train_array.shape[2],1))

mean_test = np.reshape(np.mean(test_array,axis = 1),(test_array.shape[0],test_array.shape[2],1))

mean_valid = np.reshape(np.mean(valid_array,axis = 1),(valid_array.shape[0],valid_array.shape[2],1))

std_train = np.reshape(np.std(train_array,axis = 1),(train_array.shape[0],train_array.shape[2],1))

std_test = np.reshape(np.std(test_array,axis = 1),(test_array.shape[0],test_array.shape[2],1))

std_valid = np.reshape(np.std(valid_array,axis = 1),(valid_array.shape[0],valid_array.shape[2],1))

print(mean_train.shape)




(454, 68, 1)


In [13]:
agg_train = np.concatenate((mean_train,std_train),axis = 2)
agg_test = np.concatenate((mean_test,std_test),axis = 2)
agg_valid = np.concatenate((mean_valid,std_valid),axis = 2)

In [14]:
print(agg_train.shape)

(454, 68, 2)


In [15]:
agg_train = np.reshape(agg_train,(agg_train.shape[0],agg_train.shape[1]*agg_train.shape[2]))
agg_test = np.reshape(agg_test,(agg_test.shape[0],agg_test.shape[1]*agg_test.shape[2]))
agg_valid = np.reshape(agg_valid,(agg_valid.shape[0],agg_valid.shape[1]*agg_valid.shape[2]))

In [16]:
#concatenate

train_data = np.concatenate((agg_train,agg_valid))
test_data = agg_test 




In [17]:
total_agg_feat = np.concatenate((train_data,test_data))
total_agg_labels = np.concatenate((labels_train,labels_test))

In [18]:
print(total_agg_feat.shape)

(757, 136)


Classifiers 

SVM =  gaussian and poly degree 3 or 4

Random forest and Gradient-boosting classifier.

In [19]:
 #gaussian Kernel'
 from sklearn import svm

 clf = svm.SVC(C = 1,kernel = 'rbf',verbose = 1)

 clf.fit(train_data,labels_train)

[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=1)

In [20]:
predicted_test = clf.predict(test_data)
predicted_test = predicted_test.reshape((len(predicted_test),1))
print(predicted_test.shape)


import sklearn
acc_test = sklearn.metrics.accuracy_score(predicted_test,labels_test)
print(acc_test)

(152, 1)
0.5723684210526315


In [21]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, total_agg_feat, total_agg_labels, cv=5)
print(scores)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM][LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM][0.55921053 0.58552632 0.56291391 0.57615894 0.56953642]


In [22]:
print(scores)

[0.55921053 0.58552632 0.56291391 0.57615894 0.56953642]


In [23]:
 print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.57 (+/- 0.02)


In [24]:
 #gaussian Kernel'
 from sklearn import svm

 clf = svm.SVC(C = 10,kernel = 'rbf',verbose = 1)

 clf.fit(train_data,labels_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM]

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=1)

In [25]:
predicted_test = clf.predict(test_data)
predicted_test = predicted_test.reshape((len(predicted_test),1))
print(predicted_test.shape)


import sklearn
acc_test = sklearn.metrics.accuracy_score(predicted_test,labels_test)
print(acc_test)

(152, 1)
0.6842105263157895


In [26]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, total_agg_feat, total_agg_labels, cv=5)
print(scores)

[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM][LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM][0.71710526 0.63157895 0.58278146 0.67549669 0.68211921]


In [27]:
print(scores)

[0.71710526 0.63157895 0.58278146 0.67549669 0.68211921]


In [28]:
 print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.66 (+/- 0.09)


In [29]:
 #gaussian Kernel'
 from sklearn import svm

 clf = svm.SVC(C = 100,kernel = 'rbf',verbose = 1)

 clf.fit(train_data,labels_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM]

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=1)

In [30]:
predicted_test = clf.predict(test_data)
predicted_test = predicted_test.reshape((len(predicted_test),1))
print(predicted_test.shape)


import sklearn
acc_test = sklearn.metrics.accuracy_score(predicted_test,labels_test)
print(acc_test)

(152, 1)
0.7105263157894737


In [31]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, total_agg_feat, total_agg_labels, cv=5)
print(scores)

[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM][LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM][LibSVM][0.76973684 0.70394737 0.62251656 0.72847682 0.70860927]


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [32]:
print(scores)

[0.76973684 0.70394737 0.62251656 0.72847682 0.70860927]


In [33]:
 print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.71 (+/- 0.10)


In [34]:
 #gaussian Kernel'
 from sklearn import svm

 clf = svm.SVC(C = 300,kernel = 'rbf',verbose = 1)

 clf.fit(train_data,labels_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM]

SVC(C=300, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=1)

In [35]:
predicted_test = clf.predict(test_data)
predicted_test = predicted_test.reshape((len(predicted_test),1))
print(predicted_test.shape)


import sklearn
acc_test = sklearn.metrics.accuracy_score(predicted_test,labels_test)
print(acc_test)

(152, 1)
0.7236842105263158


In [36]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, total_agg_feat, total_agg_labels, cv=5)
print(scores)

[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM][LibSVM][0.76973684 0.71052632 0.64900662 0.73509934 0.7218543 ]


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [37]:
print(scores)

[0.76973684 0.71052632 0.64900662 0.73509934 0.7218543 ]


In [38]:
 print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.72 (+/- 0.08)


In [39]:
 #gaussian Kernel'
 from sklearn import svm

 clf = svm.SVC(C = 500,kernel = 'rbf',verbose = 1)

 clf.fit(train_data,labels_train)

[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=500, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=1)

In [40]:
predicted_test = clf.predict(test_data)
predicted_test = predicted_test.reshape((len(predicted_test),1))
print(predicted_test.shape)


import sklearn
acc_test = sklearn.metrics.accuracy_score(predicted_test,labels_test)
print(acc_test)

(152, 1)
0.7236842105263158


In [41]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, total_agg_feat, total_agg_labels, cv=5)
print(scores)

[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM][LibSVM][0.76973684 0.67763158 0.65562914 0.72847682 0.7218543 ]


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [42]:
print(scores)

[0.76973684 0.67763158 0.65562914 0.72847682 0.7218543 ]


In [43]:
 print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.71 (+/- 0.08)


In [44]:
#Polynomial Kernel

from sklearn import svm

clf = svm.SVC(kernel = 'poly',verbose = 1,coef0=25)

clf.fit(train_data,labels_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM]

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=25,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=1)

In [45]:
predicted_test = clf.predict(test_data)
predicted_test = predicted_test.reshape((len(predicted_test),1))
print(predicted_test.shape)


import sklearn
acc_test = sklearn.metrics.accuracy_score(predicted_test,labels_test)
print(acc_test)

(152, 1)
0.8026315789473685


In [46]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, total_agg_feat, total_agg_labels, cv=5)
print(scores)

[LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM][LibSVM]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM][LibSVM][0.875      0.71710526 0.67549669 0.78807947 0.8013245 ]


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [47]:
print(scores)

[0.875      0.71710526 0.67549669 0.78807947 0.8013245 ]


In [48]:
 print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.77 (+/- 0.14)


Random Forest


In [49]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

clf.fit(train_data,labels_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [50]:
predicted_test = clf.predict(test_data)
predicted_test = predicted_test.reshape((len(predicted_test),1))
print(predicted_test.shape)


import sklearn
acc_test = sklearn.metrics.accuracy_score(predicted_test,labels_test)
print(acc_test)

(152, 1)
0.8947368421052632


In [51]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, total_agg_feat, total_agg_labels, cv=5)
print(scores)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:515: DataConversionWarning: A column-vector y was passed when a 

[0.90131579 0.82894737 0.81456954 0.8807947  0.89403974]


In [52]:
print(scores)

[0.90131579 0.82894737 0.81456954 0.8807947  0.89403974]


In [53]:
 print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.86 (+/- 0.07)


Gradient-boosting classifier

In [54]:
#loss= deviance

from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(loss='deviance', learning_rate=0.1, n_estimators=100, subsample=1.0, criterion='friedman_mse')

clf.fit(train_data,labels_train)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [55]:
predicted_test = clf.predict(test_data)
predicted_test = predicted_test.reshape((len(predicted_test),1))
print(predicted_test.shape)


import sklearn
acc_test = sklearn.metrics.accuracy_score(predicted_test,labels_test)
print(acc_test)

(152, 1)
0.8552631578947368


In [56]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, total_agg_feat, total_agg_labels, cv=5)
print(scores)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
 

[0.82894737 0.83552632 0.75496689 0.82781457 0.84768212]


In [57]:
print(scores)

[0.82894737 0.83552632 0.75496689 0.82781457 0.84768212]


In [58]:
 print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.82 (+/- 0.07)


Adaboost

In [59]:
#loss= deviance

from sklearn.ensemble import AdaBoostClassifier

clf = AdaBoostClassifier(n_estimators=100)

clf.fit(train_data,labels_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=100, random_state=None)

In [60]:
predicted_test = clf.predict(test_data)
predicted_test = predicted_test.reshape((len(predicted_test),1))
print(predicted_test.shape)


import sklearn
acc_test = sklearn.metrics.accuracy_score(predicted_test,labels_test)
print(acc_test)

(152, 1)
0.6776315789473685


In [61]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, total_agg_feat, total_agg_labels, cv=5)
print(scores)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

[0.58552632 0.65131579 0.54304636 0.70198675 0.67549669]


In [62]:
print(scores)

[0.58552632 0.65131579 0.54304636 0.70198675 0.67549669]


In [63]:
 print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.63 (+/- 0.12)
